"""
Product Assembly Manager
Orchestrates the creation of a complete, runnable product from user stories.
Manages shared codebase, backend/frontend integration, and product output.
"""

import os
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from datetime import datetime


class ProductAssemblyManager:
    """
    Manages the assembly of a complete product from user stories.
    Maintains shared codebase structure across story execution.
    """

    def __init__(self, project_id: str, root_dir: str = "./products", context_docs: Optional[Dict[str, str]] = None):
        """
        Initialize the product assembly manager.

        Args:
            project_id: Unique project identifier
            root_dir: Root directory for products (default: ./products)
            context_docs: Optional PRD/TRD context for README generation
        """
        self.project_id = project_id
        self.root_dir = Path(root_dir)
        self.product_dir = self.root_dir / project_id
        self.backend_dir = self.product_dir / "backend"
        self.frontend_dir = self.product_dir / "frontend"
        self.stories_implemented = {}
        self.api_endpoints = []
        self.frontend_pages = []
        self.context_docs = context_docs or {}

    def initialize_product_structure(self) -> None:
        """Create the initial product directory structure."""
        # Create directories
        self.backend_dir.mkdir(parents=True, exist_ok=True)
        self.frontend_dir.mkdir(parents=True, exist_ok=True)
        (self.backend_dir / "app" / "routes").mkdir(parents=True, exist_ok=True)
        (self.backend_dir / "tests").mkdir(parents=True, exist_ok=True)
        (self.frontend_dir / "js").mkdir(parents=True, exist_ok=True)
        (self.frontend_dir / "pages").mkdir(parents=True, exist_ok=True)

        # Create backend scaffolding
        self._create_backend_scaffold()
        # Create frontend scaffolding
        self._create_frontend_scaffold()

    def _create_backend_scaffold(self) -> None:
        """Create FastAPI backend scaffold."""
        # main.py
        main_py = '''"""
FastAPI application for {project_id}
Auto-generated by VibeFactory
""".
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager

# Import routes (will be added by stories)
# from app.routes import auth, items, etc.

# Database setup
from app.database import engine, Base

# Create tables
Base.metadata.create_all(bind=engine)

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    print("🚀 API Server starting...")
    yield
    # Shutdown
    print("🛑 API Server shutting down...")

app = FastAPI(
    title="{project_id} API",
    description="Auto-generated API from user stories",
    version="1.0.0",
    lifespan=lifespan
)

# CORS configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {{"status": "healthy"}}

# Routes will be registered here by stories

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''.format(project_id=self.project_id)

        (self.backend_dir / "app" / "main.py").write_text(main_py)

        # models.py
        models_py = '''"""
Pydantic models for {project_id}
Auto-generated by VibeFactory
"""
from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime


class BaseResponse(BaseModel):
    """Base response model for all API responses."""
    success: bool
    message: Optional[str] = None


# Story-specific models will be added here
'''.format(project_id=self.project_id)

        (self.backend_dir / "app" / "models.py").write_text(models_py)

        # database.py
        database_py = '''"""
Database configuration for {project_id}
Auto-generated by VibeFactory
"""
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import os

# Use SQLite for development
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./app.db")

engine = create_engine(
    DATABASE_URL,
    connect_args={{"check_same_thread": False}} if "sqlite" in DATABASE_URL else {{}},
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def get_db():
    """Dependency for database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
'''.format(project_id=self.project_id)

        (self.backend_dir / "app" / "database.py").write_text(database_py)

        # requirements.txt
        requirements = """fastapi==0.104.1
uvicorn[standard]==0.24.0
sqlalchemy==2.0.23
pydantic==2.5.0
python-dotenv==1.0.0
pytest==7.4.3
httpx==0.25.1
"""
        (self.backend_dir / "requirements.txt").write_text(requirements)

        # __init__.py
        (self.backend_dir / "app" / "__init__.py").write_text("")
        (self.backend_dir / "app" / "routes" / "__init__.py").write_text("")
        (self.backend_dir / "tests" / "__init__.py").write_text("")

    def _create_frontend_scaffold(self) -> None:
        """Create vanilla JavaScript frontend scaffold."""
        # index.html
        index_html = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{project_id}</title>
    <link rel="stylesheet" href="styles.css">
    <script src="js/api.js"></script>
    <script src="js/nav.js"></script>
</head>
<body>
    <nav id="navbar"></nav>
    <main id="app">
        <div id="loading" style="display: none;">Loading...</div>
        <div id="content"></div>
    </main>

    <script>
        // Initialize navigation on page load
        window.addEventListener('DOMContentLoaded', () => {{
            initializeNav();
            console.log('✅ Application initialized');
        }});
    </script>
</body>
</html>
'''.format(project_id=self.project_id)

        (self.frontend_dir / "index.html").write_text(index_html)

        # styles.css
        styles_css = '''/* Global Styles for {project_id} */

:root {{
    --primary-color: #007bff;
    --secondary-color: #6c757d;
    --success-color: #28a745;
    --danger-color: #dc3545;
    --warning-color: #ffc107;
    --info-color: #17a2b8;

    --bg-light: #f8f9fa;
    --bg-dark: #212529;
    --text-light: #f8f9fa;
    --text-dark: #212529;

    --border-radius: 4px;
    --box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}}

@media (prefers-color-scheme: dark) {{
    :root {{
        --bg-color: var(--bg-dark);
        --text-color: var(--text-light);
    }}
}}

@media (prefers-color-scheme: light) {{
    :root {{
        --bg-color: var(--bg-light);
        --text-color: var(--text-dark);
    }}
}}

* {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}

body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
    background-color: var(--bg-color, #f8f9fa);
    color: var(--text-color, #212529);
    line-height: 1.6;
}}

#navbar {{
    background-color: var(--primary-color);
    padding: 1rem;
    color: white;
    box-shadow: var(--box-shadow);
}}

#navbar nav {{
    max-width: 1200px;
    margin: 0 auto;
    display: flex;
    gap: 1rem;
}}

#navbar a {{
    color: white;
    text-decoration: none;
    padding: 0.5rem 1rem;
    border-radius: var(--border-radius);
    transition: background-color 0.2s;
}}

#navbar a:hover {{
    background-color: rgba(255, 255, 255, 0.1);
}}

main {{
    max-width: 1200px;
    margin: 2rem auto;
    padding: 0 1rem;
}}

.button {{
    background-color: var(--primary-color);
    color: white;
    padding: 0.75rem 1.5rem;
    border: none;
    border-radius: var(--border-radius);
    cursor: pointer;
    transition: background-color 0.2s;
}}

.button:hover {{
    background-color: #0056b3;
}}

.button.secondary {{
    background-color: var(--secondary-color);
}}

.form-group {{
    margin-bottom: 1rem;
}}

.form-group label {{
    display: block;
    margin-bottom: 0.5rem;
    font-weight: 500;
}}

.form-group input,
.form-group textarea,
.form-group select {{
    width: 100%;
    padding: 0.5rem;
    border: 1px solid #ddd;
    border-radius: var(--border-radius);
    font-family: inherit;
}}

.error {{
    color: var(--danger-color);
    background-color: #f8d7da;
    padding: 1rem;
    border-radius: var(--border-radius);
    margin-bottom: 1rem;
}}

.success {{
    color: var(--success-color);
    background-color: #d4edda;
    padding: 1rem;
    border-radius: var(--border-radius);
    margin-bottom: 1rem;
}}

.loading {{
    display: none;
    text-align: center;
}}
'''.format(project_id=self.project_id)

        (self.frontend_dir / "styles.css").write_text(styles_css)

        # api.js - API client helper
        api_js = '''/**
 * API Client Helper
 * Centralizes all API communication
 */

const API_BASE = window.location.origin.includes('localhost')
    ? 'http://localhost:8000'
    : '/api';

/**
 * Make API call with automatic error handling and token management
 * @param {string} method - HTTP method (GET, POST, etc.)
 * @param {string} endpoint - API endpoint path
 * @param {object} data - Request body data (optional)
 * @returns {Promise<object>} Response data
 */
async function fetchAPI(method, endpoint, data = null) {
    const url = `${API_BASE}${endpoint}`;
    const options = {
        method,
        headers: {
            'Content-Type': 'application/json',
        },
    };

    // Add auth token if available
    const token = localStorage.getItem('auth_token');
    if (token) {
        options.headers['Authorization'] = `Bearer ${token}`;
    }

    // Add body for requests that need it
    if (data && (method === 'POST' || method === 'PUT' || method === 'PATCH')) {
        options.body = JSON.stringify(data);
    }

    try {
        const response = await fetch(url, options);

        if (response.status === 401) {
            // Unauthorized - clear token and redirect to login
            localStorage.removeItem('auth_token');
            window.location.href = '/pages/login.html';
            return null;
        }

        if (!response.ok) {
            throw new Error(`API error: ${response.status} ${response.statusText}`);
        }

        return await response.json();
    } catch (error) {
        console.error('API call failed:', error);
        throw error;
    }
}

/**
 * Check if user is authenticated
 * @returns {boolean}
 */
function isAuthenticated() {
    return !!localStorage.getItem('auth_token');
}

/**
 * Get current auth token
 * @returns {string|null}
 */
function getAuthToken() {
    return localStorage.getItem('auth_token');
}

/**
 * Set auth token
 * @param {string} token
 */
function setAuthToken(token) {
    localStorage.setItem('auth_token', token);
}

/**
 * Clear auth token (logout)
 */
function clearAuthToken() {
    localStorage.removeItem('auth_token');
}
'''
        (self.frontend_dir / "js" / "api.js").write_text(api_js)

        # nav.js - Navigation management
        nav_js = '''/**
 * Navigation Management
 * Dynamically builds navigation menu from available pages
 */

const PAGES = [];

/**
 * Register a page for navigation
 * @param {string} title - Page title
 * @param {string} path - Page path
 * @param {boolean} requiresAuth - Whether page requires authentication
 */
function registerPage(title, path, requiresAuth = false) {
    PAGES.push({ title, path, requiresAuth });
}

/**
 * Initialize navigation bar
 */
function initializeNav() {
    const navbar = document.getElementById('navbar');
    if (!navbar) return;

    const nav = document.createElement('nav');
    nav.style.display = 'flex';
    nav.style.gap = '1rem';
    nav.style.alignItems = 'center';

    // Add home link (points to index, not a hardcoded dashboard)
    const homeLink = document.createElement('a');
    homeLink.href = '/index.html';
    homeLink.textContent = 'Home';
    nav.appendChild(homeLink);

    // Add page links
    PAGES.forEach(page => {
        // Skip pages that require auth if not authenticated
        if (page.requiresAuth && !isAuthenticated()) {
            return;
        }

        const link = document.createElement('a');
        link.href = page.path;
        link.textContent = page.title;
        nav.appendChild(link);
    });

    // Add spacer
    const spacer = document.createElement('div');
    spacer.style.marginLeft = 'auto';
    nav.appendChild(spacer);

    // Add auth links
    if (isAuthenticated()) {
        const logoutBtn = document.createElement('a');
        logoutBtn.href = '#';
        logoutBtn.textContent = 'Logout';
        logoutBtn.style.cursor = 'pointer';
        logoutBtn.onclick = (e) => {
            e.preventDefault();
            clearAuthToken();
            window.location.href = '/pages/login.html';
        };
        nav.appendChild(logoutBtn);
    } else {
        const loginLink = document.createElement('a');
        loginLink.href = '/pages/login.html';
        loginLink.textContent = 'Login';
        nav.appendChild(loginLink);
    }

    navbar.innerHTML = '';
    navbar.appendChild(nav);
}
'''
        (self.frontend_dir / "js" / "nav.js").write_text(nav_js)

    def add_backend_code(self, story_id: str, file_path: str, content: str) -> None:
        """
        Add backend code file for a story.

        Args:
            story_id: Story identifier
            file_path: Relative path (e.g., 'routes/auth.py')
            content: File content
        """
        full_path = self.backend_dir / "app" / file_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content)

    def add_frontend_component(self, story_id: str, file_path: str, content: str) -> None:
        """
        Add frontend component/page for a story.

        Args:
            story_id: Story identifier
            file_path: Relative path (e.g., 'pages/login.html')
            content: File content
        """
        # Sanitize UI content to strip any technical TRD information
        sanitized_content = self._sanitize_ui_content(content)
        full_path = self.frontend_dir / file_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(sanitized_content)

    def _sanitize_ui_content(self, content: str) -> str:
        """
        Remove technical TRD markers from UI content.

        This ensures that frontend code only contains user-facing content from the PRD,
        and no technical implementation details from the TRD.
        """
        tech_keywords = [
            "Technical Specification", "Architecture", "Backend", "TRD",
            "API", "Database", "SQL", "FastAPI", "JWT", "OAuth", "Auth",
            "CORS", "Middleware", "Dependency", "Session"
        ]
        # Keep lines that do not contain any technical keyword
        filtered_lines = [
            line for line in content.splitlines()
            if not any(keyword in line for keyword in tech_keywords)
        ]
        return "\n".join(filtered_lines)

    def _sanitize_readme_content(self, content: str) -> str:
        """
        Ensure README only contains PRD-derived content, not TRD technical details.

        README is user-facing and should focus on business goals, not technical implementation.
        This removes any technical sections that might have inadvertently been included.
        """
        if not content:
            return content

        # Extract just the first paragraph (business description)
        # Stop at first major section header or technical keyword
        lines = content.split('\n')
        safe_lines = []

        tech_markers = ["TRD", "Technical", "API", "FastAPI", "Database", "Schema", "Endpoint", "Authentication"]

        for line in lines:
            # Stop if we hit a section header that looks technical
            if line.startswith("###") or line.startswith("##"):
                break
            # Skip lines with technical content
            if any(marker in line for marker in tech_markers):
                continue
            safe_lines.append(line)

        # Return first non-empty result (usually first paragraph)
        result = "\n".join(safe_lines).strip()
        return result if result else "A product built with VibeFactory"

    def add_api_endpoint(self, story_id: str, endpoint_spec: Dict) -> None:
        """
        Register an API endpoint for this story.

        Args:
            story_id: Story identifier
            endpoint_spec: Endpoint specification dict
        """
        self.api_endpoints.append({
            'story_id': story_id,
            'spec': endpoint_spec
        })

    def add_frontend_page(self, story_id: str, page_name: str, page_path: str) -> None:
        """
        Register a frontend page for this story.

        Args:
            story_id: Story identifier
            page_name: Display name of page
            page_path: Path to page HTML file
        """
        self.frontend_pages.append({
            'story_id': story_id,
            'name': page_name,
            'path': page_path
        })

    def register_story(self, story_id: str, story_data: Dict) -> None:
        """
        Register a completed story.

        Args:
            story_id: Story identifier
            story_data: Story data dict
        """
        self.stories_implemented[story_id] = {
            'data': story_data,
            'timestamp': datetime.now().isoformat()
        }

    def generate_mandatory_ui(self) -> None:
        """
        Update navigation with registered pages.
        Only runs for dynamic (SPA) products that have a nav.js scaffold.
        Skipped entirely for static products (ads, flyers, single-file HTML).
        """
        nav_js_path = self.frontend_dir / "js" / "nav.js"
        if not nav_js_path.exists():
            # Static product — no nav framework, nothing to update
            return

        # Update nav.js with registered pages
        nav_js = self._read_file(nav_js_path)

        # Add page registrations
        page_registrations = ""
        for page in self.frontend_pages:
            page_registrations += f"registerPage('{page['name']}', '{page['path']}');\n"

        if page_registrations:
            nav_js += f"\n// Auto-registered pages\n{page_registrations}"
            (self.frontend_dir / "js" / "nav.js").write_text(nav_js)


    def export_product(self) -> str:
        """
        Export complete product with supporting files.

        Returns:
            Path to exported product directory
        """
        self.generate_mandatory_ui()

        # Determine if this is a static or dynamic product
        has_backend = len(self.api_endpoints) > 0 or self.backend_dir.exists() and any(self.backend_dir.rglob('*.py'))

        # Create docker-compose.yml (only for products with backend)
        if has_backend:
            docker_compose = f'''version: '3.8'

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
    volumes:
      - ./backend:/workspace
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    image: python:3.11-slim
    working_dir: /workspace
    command: python -m http.server 8080 -d /workspace/frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/workspace/frontend

volumes:
  db:
'''
            (self.product_dir / "docker-compose.yml").write_text(docker_compose)

        # Create start.sh
        if has_backend:
            start_sh = f'''#!/bin/bash
# Launch {self.project_id} product

echo "🚀 Starting {self.project_id}..."
echo ""
echo "Backend API: http://localhost:8000"
echo "Frontend UI: http://localhost:8080"
echo ""
echo "Press Ctrl+C to stop"
echo ""

docker-compose up --build
'''
        else:
            # Static product - just serve frontend
            start_sh = f'''#!/bin/bash
# Launch {self.project_id} product (static frontend)

echo "🚀 Starting {self.project_id}..."
echo ""
echo "Frontend UI: http://localhost:8080"
echo ""
echo "Press Ctrl+C to stop"
echo ""

python -m http.server 8080 -d frontend
'''
        start_sh_path = self.product_dir / "start.sh"
        start_sh_path.write_text(start_sh)
        os.chmod(start_sh_path, 0o755)

        # Create README
        if has_backend:
            project_type = "Full-Stack Application"
            structure_section = """## Project Structure

- `backend/` - FastAPI REST API
- `frontend/` - Vanilla JavaScript web UI
- `docker-compose.yml` - Local development environment
"""
            endpoints_section = f"""
## API Endpoints

{chr(10).join(f"- {ep['spec'].get('method', 'GET')} {ep['spec'].get('path', '')}" for ep in self.api_endpoints)}
"""
            customization_section = """
## Customization

Edit files in `backend/app/` and `frontend/` as needed. Changes auto-reload in development mode.
"""
        else:
            project_type = "Static Frontend"
            structure_section = """## Project Structure

- `frontend/` - Vanilla HTML/CSS/JavaScript web UI (no backend required)
"""
            endpoints_section = ""
            customization_section = """
## Customization

Edit files in `frontend/` as needed. No backend compilation required.
"""

                # Build a clean project description from PRD ONLY (never TRD)
        # IMPORTANT: README is user-facing and must reflect business goals, not technical implementation
        prd_content = self.context_docs.get("PRD", self.context_docs.get("prd", ""))
        # Extract first paragraph from PRD for description
        project_description = (prd_content[:500] if prd_content else f"Auto-generated {project_type} from VibeFactory")
        # Sanitize to remove any technical markers that might have slipped through
        project_description = self._sanitize_readme_content(project_description)

        readme = f'''# {self.project_id}

{project_description}

## Quick Start

```bash
cd products/{self.project_id}
bash start.sh
```

Then open http://localhost:8080

{structure_section}
## Implemented Stories

{chr(10).join(f"- {s.get('name', sid)}: {s.get('description', '')[:200].replace(chr(10),' ')}" for sid, s in [(k, v['data']) for k, v in self.stories_implemented.items()])}{endpoints_section}{customization_section}
'''
        (self.product_dir / "README.md").write_text(readme)

        # Create .gitignore
        gitignore = '''*.db
__pycache__/
.env
.venv
venv/
node_modules/
.DS_Store
'''
        (self.product_dir / ".gitignore").write_text(gitignore)

        return str(self.product_dir)

    def _read_file(self, path: Path) -> str:
        """Read file content."""
        if path.exists():
            return path.read_text()
        return ""
